apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-sa
  namespace: saas-platform
  annotations:
    # IAM Role ARN linked to IRSA configurations
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/pod-irsa-role"
